### ISSUE TITLE
API-Testing-Last Name field is kept blank but User is getting registered

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#40]
Hi @Jebisha123,

User is getting registered if lastname is kept blank.

Steps to Reproduce:
1)Open postman and send post request for register
2)In Body(raw),fill all fields with valid input and keep last name blank
3)Response is received: 201:created and message appears as : User registered

Below are the screenshots attached.

![api_issue](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/85754bc9-ac2e-4cc8-8143-d3ad9560c8a0)
![database](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/129a6a12-94db-40d8-8f2a-fcd6a313c271)

Thanks,
Priya

**Comment by Jebisha123** [comment]
Resolved and updated code in github

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/9de12ab6-b8fb-421c-add6-76f65f88fbe2)
Hi Merry,

This issue is still present.So,reopening this defect.

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/a80fec3b-9b37-423d-9cb1-38eb1b185569)
 working fine.So,closing this defect.
