### ISSUE TITLE
API Testing-User is getting registered with empty first name

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#41]
![2](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/2e18d19e-de0c-4b95-8b16-1b9138602942)
Hi @Jebisha123,

User is getting registered if firstname is kept blank.

Steps to Reproduce:
1)Open postman and send post request for register
2)In Body(raw),fill all fields with valid input and keep first
![1](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/495851aa-4dce-41d1-8b0f-66c7f50a7834)
 name blank
3)Response is received: 201:created and message appears as : User registered

Below are the screenshots attached.

**Comment by Jebisha123** [comment]
Resolved and updated code in github

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/671875ba-57a7-4e5b-94f6-6d22206274c0)

Hi Merry,
This issue is still persisting,So,reopening this issue.

**Comment by priyadhawan06** [comment]
Working fine,so,closing this defect.
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/75728c35-009b-4990-90a9-da016e0ee38e)
