### ISSUE TITLE
API Testing-User is getting registered if Firstname and Lastname are kept blank

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#42]
Hi Merry,

-User is getting registered if Firstname and Lastname are kept blank

Steps to Reproduce:

1)Open postman and send post request for register
2)In Body(raw),fill all fields with valid input and keep last name blank
3)Response is received: 201:created and message appears as : User registered

Below are the screenshots attached.

![3](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/5806348d-240e-4742-b729-30a3ac918e09)
![4](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/15c6adc7-3b40-48c0-93dd-56ddb51525f4)

**Comment by Jebisha123** [comment]
Resolved and updated code in github

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/dbca57a8-036f-42b7-87f5-4d0a229a7c69)

Hi Merry,
This issue is still persisting.So,reopening this defect.

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/70f2439b-7024-444e-8a12-6cb4e9bdecaf)
 working fine.So,closing this issue.
