### ISSUE TITLE
API Testing: Error message for password field in registeration page is reflecting in text format instead of JSON

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#68]
Hi @Jebisha123 ,

While adding invalid password,response error is coming in Text format

Steps to Reproduce:
1)Enter invalid password

registeration will fail and error message is coming in text format instead of JSON

Screenshot attached:
![04](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/9aad55b5-cae0-48bb-91a1-1169fdc6855e)

**Comment by Jebisha123** [comment]
Resolved and updated code in github

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/84480124-ceb3-4ec5-86c3-ab70b0db89de)

Hi Merry,I have rechecked it and error is still persisting.So,reopening this defect.

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
Its working as expected.So,closing this defect.
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/29fe9d6b-67d1-40c1-a730-ef327f85d0f0)
